-- Проверка Advance Charge для SUB-61996030217
SELECT 
    CONTRACT_ID,
    ICC_ID_IMEI,
    TO_CHAR(INVOICE_DATE, 'YYYYMM') AS bill_month,
    DESCRIPTION,
    AMOUNT,
    TRANSACTION_DATE,
    FEE_TYPE,
    COUNT(*) AS duplicate_count,
    LISTAGG(ID, ', ') WITHIN GROUP (ORDER BY ID) AS ids
FROM STECCOM_EXPENSES
WHERE CONTRACT_ID = 'SUB-61996030217'
  AND ICC_ID_IMEI = '300234069209690'
  AND UPPER(TRIM(DESCRIPTION)) LIKE '%ADVANCE CHARGE%'
GROUP BY CONTRACT_ID, ICC_ID_IMEI, TO_CHAR(INVOICE_DATE, 'YYYYMM'), DESCRIPTION, AMOUNT, TRANSACTION_DATE, FEE_TYPE
ORDER BY TRANSACTION_DATE;

-- Проверка агрегации после удаления дубликатов
SELECT 
    TO_CHAR(INVOICE_DATE, 'YYYYMM') AS bill_month,
    CONTRACT_ID,
    ICC_ID_IMEI AS imei,
    SUM(CASE WHEN UPPER(TRIM(DESCRIPTION)) LIKE '%ADVANCE CHARGE%' OR UPPER(TRIM(DESCRIPTION)) = 'ADVANCE CHARGE' THEN AMOUNT ELSE 0 END) AS fee_advance_charge
FROM (
    SELECT se.*,
        ROW_NUMBER() OVER (
            PARTITION BY 
                TO_CHAR(se.INVOICE_DATE, 'YYYYMM'),
                se.CONTRACT_ID,
                se.ICC_ID_IMEI,
                UPPER(TRIM(se.DESCRIPTION)),
                se.AMOUNT,
                se.TRANSACTION_DATE
            ORDER BY se.ID
        ) AS rn
    FROM STECCOM_EXPENSES se
    WHERE se.CONTRACT_ID = 'SUB-61996030217'
      AND se.ICC_ID_IMEI = '300234069209690'
      AND se.INVOICE_DATE IS NOT NULL
      AND (se.SERVICE IS NULL OR UPPER(TRIM(se.SERVICE)) != 'BROADBAND')
) se
WHERE se.rn = 1
GROUP BY TO_CHAR(INVOICE_DATE, 'YYYYMM'), CONTRACT_ID, ICC_ID_IMEI;




