-- ============================================================================
-- STECCOM_EXPENSES - Таблица расходов STECCOM
-- Назначение: Хранение данных для тестирования (копия из Oracle)
-- База данных: PostgreSQL (testing)
-- ============================================================================

-- Удаление если существует
DROP TABLE IF EXISTS STECCOM_EXPENSES CASCADE;

CREATE TABLE STECCOM_EXPENSES (
    ID SERIAL PRIMARY KEY,
    INVOICE_DATE DATE,
    COMPANY_NAME VARCHAR(200),
    COMPANY_NUMBER INTEGER,
    SETTLING_PERIOD INTEGER,
    FEE_TYPE VARCHAR(100),
    CONTRACT_ID VARCHAR(50),
    IMSI_ISDNA VARCHAR(50),
    ICC_ID_IMEI VARCHAR(50),
    ACTIVATION_DATE DATE,
    TRANSACTION_DATE DATE,
    SERVICE VARCHAR(100),
    RATE_TYPE VARCHAR(100),
    PLAN_DISCOUNT VARCHAR(100),
    DESCRIPTION VARCHAR(500),
    PRORATED_DAYS INTEGER,
    AMOUNT NUMERIC(10,2),
    GROUP_NAME VARCHAR(100),
    SOURCE_FILE VARCHAR(200),
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50) DEFAULT CURRENT_USER
);

-- Индексы
CREATE INDEX idx_steccom_imei ON STECCOM_EXPENSES(ICC_ID_IMEI);
CREATE INDEX idx_steccom_contract ON STECCOM_EXPENSES(CONTRACT_ID);
CREATE INDEX idx_steccom_invoice_date ON STECCOM_EXPENSES(INVOICE_DATE);
CREATE INDEX idx_steccom_description ON STECCOM_EXPENSES(DESCRIPTION);

-- Комментарии
COMMENT ON TABLE STECCOM_EXPENSES IS 'Таблица расходов STECCOM - биллинг данные Iridium M2M (тестовая копия)';
COMMENT ON COLUMN STECCOM_EXPENSES.CONTRACT_ID IS 'ID контракта';
COMMENT ON COLUMN STECCOM_EXPENSES.ICC_ID_IMEI IS 'IMEI номер устройства';
COMMENT ON COLUMN STECCOM_EXPENSES.INVOICE_DATE IS 'Дата инвойса';
COMMENT ON COLUMN STECCOM_EXPENSES.ACTIVATION_DATE IS 'Дата активации';
COMMENT ON COLUMN STECCOM_EXPENSES.AMOUNT IS 'Сумма расходов (USD)';

\echo 'Таблица STECCOM_EXPENSES создана успешно!'


