-- ============================================================================
-- check_sbd1_overage_calculation.sql
-- Проверка расчета Calc overage для SBD-1 и SBD-10
-- ============================================================================

SET PAGESIZE 200
SET FEEDBACK ON
SET HEADING ON
SET LINESIZE 2000

PROMPT === 1. Проверка наличия тарифов SBD-1 и SBD-10 в TARIFF_PLANS ===

SELECT 
    PLAN_NAME,
    PLAN_CODE,
    INCLUDED_KB,
    TIER1_FROM_KB,
    TIER1_TO_KB,
    TIER1_PRICE_USD,
    TIER2_FROM_KB,
    TIER2_TO_KB,
    TIER2_PRICE_USD,
    TIER3_FROM_KB,
    TIER3_PRICE_USD,
    ACTIVE
FROM TARIFF_PLANS
WHERE PLAN_CODE IN ('SBD-1', 'SBD-10')
ORDER BY PLAN_CODE;

PROMPT
PROMPT === 2. Проверка расчета CALCULATED_OVERAGE для SBD-1 и SBD-10 ===
PROMPT (по данным из V_SPNET_OVERAGE_ANALYSIS)

SELECT 
    PLAN_NAME,
    PLAN_CODE,
    COUNT(*) AS RECORD_COUNT,
    SUM(TRAFFIC_USAGE_BYTES) AS TOTAL_TRAFFIC_BYTES,
    SUM(TOTAL_USAGE_KB) AS TOTAL_USAGE_KB,
    SUM(OVERAGE_KB) AS TOTAL_OVERAGE_KB,
    ROUND(SUM(CALCULATED_OVERAGE_CHARGE), 2) AS TOTAL_CALCULATED_OVERAGE,
    ROUND(SUM(SPNET_TOTAL_AMOUNT), 2) AS TOTAL_SPNET_AMOUNT
FROM V_SPNET_OVERAGE_ANALYSIS
WHERE PLAN_CODE IN ('SBD-1', 'SBD-10')
GROUP BY PLAN_NAME, PLAN_CODE
ORDER BY PLAN_CODE;

PROMPT
PROMPT === 3. Детализация по CONTRACT_ID для SBD-1 ===

SELECT 
    CONTRACT_ID,
    IMEI,
    BILL_MONTH,
    PLAN_NAME,
    PLAN_CODE,
    TOTAL_USAGE_KB,
    INCLUDED_KB,
    OVERAGE_KB,
    CALCULATED_OVERAGE_CHARGE,
    SPNET_TOTAL_AMOUNT
FROM V_SPNET_OVERAGE_ANALYSIS
WHERE PLAN_CODE = 'SBD-1'
  AND OVERAGE_KB > 0
ORDER BY BILL_MONTH DESC, CALCULATED_OVERAGE_CHARGE DESC
FETCH FIRST 20 ROWS ONLY;

PROMPT
PROMPT === 4. Детализация по CONTRACT_ID для SBD-10 ===

SELECT 
    CONTRACT_ID,
    IMEI,
    BILL_MONTH,
    PLAN_NAME,
    PLAN_CODE,
    TOTAL_USAGE_KB,
    INCLUDED_KB,
    OVERAGE_KB,
    CALCULATED_OVERAGE_CHARGE,
    SPNET_TOTAL_AMOUNT
FROM V_SPNET_OVERAGE_ANALYSIS
WHERE PLAN_CODE = 'SBD-10'
  AND OVERAGE_KB > 0
ORDER BY BILL_MONTH DESC, CALCULATED_OVERAGE_CHARGE DESC
FETCH FIRST 20 ROWS ONLY;

PROMPT
PROMPT === 5. Проверка функции CALCULATE_OVERAGE для SBD-1 ===

SELECT 
    'SBD-1, 5 KB (5000 bytes)' AS test_case,
    CALCULATE_OVERAGE('SBD Tiered 1250 1K', 5000) AS calculated_overage,
    6.00 AS expected_overage,
    ROUND(CALCULATE_OVERAGE('SBD Tiered 1250 1K', 5000) - 6.00, 2) AS diff
FROM DUAL
UNION ALL
SELECT 
    'SBD-1, 15 KB (15000 bytes)',
    CALCULATE_OVERAGE('SBD Tiered 1250 1K', 15000),
    19.25,
    ROUND(CALCULATE_OVERAGE('SBD Tiered 1250 1K', 15000) - 19.25, 2)
FROM DUAL
UNION ALL
SELECT 
    'SBD-1, 30 KB (30000 bytes)',
    CALCULATE_OVERAGE('SBD Tiered 1250 1K', 30000),
    27.25,
    ROUND(CALCULATE_OVERAGE('SBD Tiered 1250 1K', 30000) - 27.25, 2)
FROM DUAL
UNION ALL
SELECT 
    'SBD-10, 35 KB (35000 bytes)',
    CALCULATE_OVERAGE('SBD Tiered 1250 10K', 35000),
    6.50,
    ROUND(CALCULATE_OVERAGE('SBD Tiered 1250 10K', 35000) - 6.50, 2)
FROM DUAL;

PROMPT
PROMPT === 6. Проверка данных в V_CONSOLIDATED_REPORT_WITH_BILLING ===
PROMPT (сумма CALCULATED_OVERAGE по тарифам)

SELECT 
    PLAN_NAME,
    COUNT(*) AS RECORD_COUNT,
    ROUND(SUM(CALCULATED_OVERAGE), 2) AS TOTAL_CALCULATED_OVERAGE,
    ROUND(SUM(SPNET_TOTAL_AMOUNT), 2) AS TOTAL_SPNET_AMOUNT
FROM V_CONSOLIDATED_REPORT_WITH_BILLING
WHERE PLAN_NAME IN ('SBD Tiered 1250 1K', 'SBD Tiered 1250 10K')
  AND CALCULATED_OVERAGE > 0
GROUP BY PLAN_NAME
ORDER BY PLAN_NAME;

PROMPT
PROMPT === 7. Сравнение: есть ли записи с PLAN_NAME = 'SBD Tiered 1250 1K' но без расчета? ===

SELECT 
    cor.CONTRACT_ID,
    cor.IMEI,
    cor.BILL_MONTH,
    cor.PLAN_NAME,
    cor.TOTAL_USAGE_KB,
    cor.OVERAGE_KB,
    cor.CALCULATED_OVERAGE,
    cor.SPNET_TOTAL_AMOUNT,
    CASE 
        WHEN cor.OVERAGE_KB > 0 AND cor.CALCULATED_OVERAGE = 0 THEN 'ПРОБЛЕМА: Есть превышение, но нет расчета!'
        WHEN cor.OVERAGE_KB = 0 AND cor.CALCULATED_OVERAGE > 0 THEN 'ПРОБЛЕМА: Нет превышения, но есть расчет!'
        ELSE 'OK'
    END AS STATUS
FROM V_CONSOLIDATED_OVERAGE_REPORT cor
WHERE cor.PLAN_NAME = 'SBD Tiered 1250 1K'
  AND (cor.OVERAGE_KB > 0 OR cor.CALCULATED_OVERAGE > 0)
ORDER BY cor.BILL_MONTH DESC, cor.CALCULATED_OVERAGE DESC
FETCH FIRST 30 ROWS ONLY;

EXIT;



