-- Проверка источника данных для записи с IMEI 300534067885480, CONTRACT_ID SUB-62005190142
-- Проверяем, откуда берется BILL_MONTH = 2025-11

-- 1. Проверка в SPNet данных
SELECT 
    'SPNet' AS source,
    sp.IMEI,
    sp.CONTRACT_ID,
    sp.BILL_MONTH,
    sp.PLAN_NAME
FROM V_CONSOLIDATED_OVERAGE_REPORT sp
WHERE sp.IMEI = '300534067885480'
  AND sp.CONTRACT_ID = 'SUB-62005190142'
  AND sp.BILL_MONTH = '202511';

-- 2. Проверка в STECCOM данных (исходная таблица)
SELECT 
    'STECCOM_EXPENSES' AS source,
    se.ICC_ID_IMEI AS IMEI,
    se.CONTRACT_ID,
    se.INVOICE_DATE,
    TO_CHAR(se.INVOICE_DATE, 'YYYYMM') AS calculated_bill_month_current,
    TO_CHAR(ADD_MONTHS(se.INVOICE_DATE, -1), 'YYYYMM') AS calculated_bill_month_previous,
    se.SOURCE_FILE,
    se.DESCRIPTION,
    se.AMOUNT
FROM STECCOM_EXPENSES se
WHERE se.ICC_ID_IMEI = '300534067885480'
  AND se.CONTRACT_ID = 'SUB-62005190142'
  AND (se.INVOICE_DATE >= DATE '2025-10-01' AND se.INVOICE_DATE <= DATE '2025-11-30')
ORDER BY se.INVOICE_DATE DESC;

-- 3. Проверка в V_CONSOLIDATED_OVERAGE_REPORT
SELECT 
    'V_CONSOLIDATED_OVERAGE_REPORT' AS source,
    cor.IMEI,
    cor.CONTRACT_ID,
    cor.BILL_MONTH,
    cor.PLAN_NAME
FROM V_CONSOLIDATED_OVERAGE_REPORT cor
WHERE cor.IMEI = '300534067885480'
  AND cor.CONTRACT_ID = 'SUB-62005190142'
ORDER BY cor.BILL_MONTH DESC;

-- 4. Проверка в V_CONSOLIDATED_REPORT_WITH_BILLING
SELECT 
    'V_CONSOLIDATED_REPORT_WITH_BILLING' AS source,
    v.IMEI,
    v.CONTRACT_ID,
    v.BILL_MONTH,
    v.BILL_MONTH_YYYMM,
    v.FEE_ADVANCE_CHARGE
FROM V_CONSOLIDATED_REPORT_WITH_BILLING v
WHERE v.IMEI = '300534067885480'
  AND v.CONTRACT_ID = 'SUB-62005190142'
ORDER BY v.BILL_MONTH DESC;

