-- Проверка данных для IMEI 301434061220930 с INVOICE_DATE = 2025-11-02
-- Должен быть BILL_MONTH = 2025-10, FINANCIAL_PERIOD = 2025-09

-- 1. Проверка в исходной таблице
SELECT 
    'STECCOM_EXPENSES' AS source_table,
    se.ICC_ID_IMEI AS IMEI,
    se.CONTRACT_ID,
    se.INVOICE_DATE,
    TO_CHAR(ADD_MONTHS(se.INVOICE_DATE, -1), 'YYYYMM') AS calculated_bill_month,
    TO_CHAR(ADD_MONTHS(se.INVOICE_DATE, -1), 'YYYY-MM') AS calculated_bill_month_formatted,
    se.DESCRIPTION,
    se.AMOUNT
FROM STECCOM_EXPENSES se
WHERE se.ICC_ID_IMEI = '301434061220930'
  AND se.INVOICE_DATE = DATE '2025-11-02'
  AND (se.DESCRIPTION = 'Prorated' OR se.DESCRIPTION = 'Advance Charge')
  AND se.AMOUNT > 0;

-- 2. Проверка в V_CONSOLIDATED_OVERAGE_REPORT
SELECT 
    'V_CONSOLIDATED_OVERAGE_REPORT' AS source_table,
    cor.IMEI,
    cor.CONTRACT_ID,
    cor.BILL_MONTH
FROM V_CONSOLIDATED_OVERAGE_REPORT cor
WHERE cor.IMEI = '301434061220930'
  AND cor.BILL_MONTH = '202510'
ORDER BY cor.BILL_MONTH DESC;

-- 3. Проверка в V_CONSOLIDATED_REPORT_WITH_BILLING
SELECT 
    'V_CONSOLIDATED_REPORT_WITH_BILLING' AS source_table,
    v.IMEI,
    v.CONTRACT_ID,
    v.BILL_MONTH,
    v.BILL_MONTH_YYYMM,
    v.FINANCIAL_PERIOD,
    v.FEE_ADVANCE_CHARGE,
    v.FEE_PRORATED
FROM V_CONSOLIDATED_REPORT_WITH_BILLING v
WHERE v.IMEI = '301434061220930'
  AND (v.BILL_MONTH = '2025-10' OR v.BILL_MONTH_YYYMM = '202510')
ORDER BY v.BILL_MONTH DESC;

-- 4. Проверка всех периодов для этого IMEI
SELECT 
    v.BILL_MONTH,
    v.BILL_MONTH_YYYMM,
    v.FINANCIAL_PERIOD,
    COUNT(*) AS record_count
FROM V_CONSOLIDATED_REPORT_WITH_BILLING v
WHERE v.IMEI = '301434061220930'
GROUP BY v.BILL_MONTH, v.BILL_MONTH_YYYMM, v.FINANCIAL_PERIOD
ORDER BY v.BILL_MONTH DESC;

