-- Проверка данных с INVOICE_DATE = 2025-11-02 для IMEI 301434061220930

-- 1. Проверка в исходной таблице
SELECT 
    'STECCOM_EXPENSES' AS source,
    se.ICC_ID_IMEI AS IMEI,
    se.CONTRACT_ID,
    se.INVOICE_DATE,
    TO_CHAR(ADD_MONTHS(se.INVOICE_DATE, -1), 'YYYYMM') AS calculated_bill_month,
    TO_CHAR(ADD_MONTHS(se.INVOICE_DATE, -1), 'YYYY-MM') AS calculated_bill_month_formatted,
    se.DESCRIPTION,
    se.AMOUNT
FROM STECCOM_EXPENSES se
WHERE se.ICC_ID_IMEI = '301434061220930'
  AND se.INVOICE_DATE = DATE '2025-11-02';

-- 2. Проверка в steccom_data CTE (часть V_CONSOLIDATED_OVERAGE_REPORT)
SELECT 
    'steccom_data check' AS source,
    se.ICC_ID_IMEI AS IMEI,
    se.CONTRACT_ID,
    TO_CHAR(ADD_MONTHS(se.INVOICE_DATE, -1), 'YYYYMM') AS calculated_bill_month
FROM STECCOM_EXPENSES se
WHERE se.ICC_ID_IMEI = '301434061220930'
  AND se.INVOICE_DATE = DATE '2025-11-02'
  AND se.ICC_ID_IMEI IS NOT NULL
  AND (se.SERVICE IS NULL OR UPPER(TRIM(se.SERVICE)) != 'BROADBAND')
GROUP BY se.ICC_ID_IMEI, se.CONTRACT_ID, TO_CHAR(ADD_MONTHS(se.INVOICE_DATE, -1), 'YYYYMM');

-- 3. Проверка в V_CONSOLIDATED_OVERAGE_REPORT
SELECT 
    'V_CONSOLIDATED_OVERAGE_REPORT' AS source,
    cor.IMEI,
    cor.CONTRACT_ID,
    cor.BILL_MONTH
FROM V_CONSOLIDATED_OVERAGE_REPORT cor
WHERE cor.IMEI = '301434061220930'
  AND cor.BILL_MONTH = '202510';

-- 4. Проверка в V_CONSOLIDATED_REPORT_WITH_BILLING
SELECT 
    'V_CONSOLIDATED_REPORT_WITH_BILLING' AS source,
    v.IMEI,
    v.CONTRACT_ID,
    v.BILL_MONTH,
    v.BILL_MONTH_YYYMM,
    v.FINANCIAL_PERIOD,
    v.FEE_ADVANCE_CHARGE
FROM V_CONSOLIDATED_REPORT_WITH_BILLING v
WHERE v.IMEI = '301434061220930'
  AND (v.BILL_MONTH = '2025-10' OR v.BILL_MONTH_YYYMM = '202510' OR v.FINANCIAL_PERIOD = '2025-10');

