-- Проверка почему IMEI 301434061220930 не находится в отчете
-- Данные есть в STECCOM_EXPENSES с INVOICE_DATE = 2025-11-02

-- 1. Проверка в steccom_data (часть V_CONSOLIDATED_OVERAGE_REPORT)
SELECT 
    'steccom_data check' AS check_type,
    se.ICC_ID_IMEI AS IMEI,
    se.CONTRACT_ID,
    TO_CHAR(ADD_MONTHS(se.INVOICE_DATE, -1), 'YYYYMM') AS calculated_bill_month,
    COUNT(*) AS record_count
FROM STECCOM_EXPENSES se
WHERE se.ICC_ID_IMEI = '301434061220930'
  AND se.INVOICE_DATE = DATE '2025-11-02'
  AND se.ICC_ID_IMEI IS NOT NULL
  AND (se.SERVICE IS NULL OR UPPER(TRIM(se.SERVICE)) != 'BROADBAND')
GROUP BY se.ICC_ID_IMEI, se.CONTRACT_ID, TO_CHAR(ADD_MONTHS(se.INVOICE_DATE, -1), 'YYYYMM');

-- 2. Проверка в V_CONSOLIDATED_OVERAGE_REPORT
SELECT 
    'V_CONSOLIDATED_OVERAGE_REPORT' AS check_type,
    cor.IMEI,
    cor.CONTRACT_ID,
    cor.BILL_MONTH,
    COUNT(*) AS record_count
FROM V_CONSOLIDATED_OVERAGE_REPORT cor
WHERE cor.IMEI = '301434061220930'
  AND cor.BILL_MONTH = '202510'
GROUP BY cor.IMEI, cor.CONTRACT_ID, cor.BILL_MONTH;

-- 3. Проверка в V_CONSOLIDATED_REPORT_WITH_BILLING с FINANCIAL_PERIOD = 2025-09
SELECT 
    'V_CONSOLIDATED_REPORT_WITH_BILLING' AS check_type,
    v.IMEI,
    v.CONTRACT_ID,
    v.BILL_MONTH,
    v.FINANCIAL_PERIOD,
    v.FEE_ADVANCE_CHARGE,
    v.FEE_PRORATED
FROM V_CONSOLIDATED_REPORT_WITH_BILLING v
WHERE v.IMEI = '301434061220930'
  AND v.FINANCIAL_PERIOD = '2025-09';

-- 4. Проверка всех записей для этого IMEI
SELECT 
    v.BILL_MONTH,
    v.FINANCIAL_PERIOD,
    COUNT(*) AS record_count
FROM V_CONSOLIDATED_REPORT_WITH_BILLING v
WHERE v.IMEI = '301434061220930'
GROUP BY v.BILL_MONTH, v.FINANCIAL_PERIOD
ORDER BY v.BILL_MONTH DESC;

-- 5. Проверка JOIN условий - есть ли CONTRACT_ID в биллинге?
SELECT 
    'Billing check' AS check_type,
    v.CONTRACT_ID,
    COUNT(*) AS service_count
FROM V_IRIDIUM_SERVICES_INFO v
WHERE v.CONTRACT_ID = 'SUB-54560555424'
GROUP BY v.CONTRACT_ID;

