-- Тестовый запрос для проверки исправлений
SELECT 
    v.FINANCIAL_PERIOD,
    v.BILL_MONTH AS "INVOICE_MONTH",
    v.IMEI,
    v.FEE_ADVANCE_CHARGE
FROM V_CONSOLIDATED_REPORT_WITH_BILLING v
WHERE v.IMEI = '301434061220930'
  AND v.FINANCIAL_PERIOD = '2025-10'
ORDER BY v.BILL_MONTH DESC;

