-- ============================================================================
-- V_CONSOLIDATED_REPORT_WITH_BILLING
-- Расширенный отчет с данными из биллинга (название клиента, договор, код 1С)
-- База данных: Oracle (billing7@bm7)
-- ============================================================================

SET SQLBLANKLINES ON
SET DEFINE OFF

CREATE OR REPLACE VIEW V_CONSOLIDATED_REPORT_WITH_BILLING AS
WITH -- Агрегируем fees из STECCOM_EXPENSES по типам для каждого периода
steccom_fees AS (
    SELECT 
        TO_CHAR(se.INVOICE_DATE, 'YYYYMM') AS bill_month,
        se.CONTRACT_ID,
        se.ICC_ID_IMEI AS imei,
        SUM(CASE WHEN UPPER(TRIM(se.DESCRIPTION)) LIKE '%ACTIVATION%' OR UPPER(TRIM(se.DESCRIPTION)) = 'ACTIVATION FEE' THEN se.AMOUNT ELSE 0 END) AS fee_activation_fee,
        SUM(CASE WHEN UPPER(TRIM(se.DESCRIPTION)) LIKE '%ADVANCE CHARGE%' OR UPPER(TRIM(se.DESCRIPTION)) = 'ADVANCE CHARGE' THEN se.AMOUNT ELSE 0 END) AS fee_advance_charge,
        SUM(CASE WHEN UPPER(TRIM(se.DESCRIPTION)) LIKE '%CREDIT%' AND UPPER(TRIM(se.DESCRIPTION)) NOT LIKE '%CREDITED%' THEN se.AMOUNT ELSE 0 END) AS fee_credit,
        SUM(CASE WHEN UPPER(TRIM(se.DESCRIPTION)) LIKE '%CREDITED%' THEN se.AMOUNT ELSE 0 END) AS fee_credited,
        SUM(CASE WHEN UPPER(TRIM(se.DESCRIPTION)) LIKE '%PRORATED%' OR UPPER(TRIM(se.DESCRIPTION)) = 'PRORATED' THEN se.AMOUNT ELSE 0 END) AS fee_prorated,
        SUM(se.AMOUNT) AS fees_total
    FROM STECCOM_EXPENSES se
    WHERE se.CONTRACT_ID IS NOT NULL
      AND se.ICC_ID_IMEI IS NOT NULL
      AND se.INVOICE_DATE IS NOT NULL
      AND (se.SERVICE IS NULL OR UPPER(TRIM(se.SERVICE)) != 'BROADBAND')
    GROUP BY TO_CHAR(se.INVOICE_DATE, 'YYYYMM'), se.CONTRACT_ID, se.ICC_ID_IMEI
)
SELECT 
    -- Bill Month в формате YYYY-MM для отображения
    CASE 
        WHEN cor.BILL_MONTH IS NOT NULL THEN
            SUBSTR(LPAD(TO_CHAR(cor.BILL_MONTH), 6, '0'), 1, 4) || '-' || SUBSTR(LPAD(TO_CHAR(cor.BILL_MONTH), 6, '0'), 5, 2)
        ELSE NULL
    END AS BILL_MONTH,
    -- Сохраняем оригинальный формат для связи (YYYYMM как число)
    cor.BILL_MONTH AS BILL_MONTH_YYYMM,
    cor.IMEI,
    cor.CONTRACT_ID,
    cor.PLAN_NAME,
    -- Разделение трафика и событий (по каждому периоду)
    cor.TRAFFIC_USAGE_BYTES,
    cor.EVENTS_COUNT,
    cor.DATA_USAGE_EVENTS,
    cor.MAILBOX_EVENTS,
    cor.REGISTRATION_EVENTS,
    -- Суммы и превышения
    cor.SPNET_TOTAL_AMOUNT,
    cor.INCLUDED_KB,
    cor.TOTAL_USAGE_KB,
    cor.OVERAGE_KB,
    cor.CALCULATED_OVERAGE,
    cor.STECCOM_MONTHLY_AMOUNT,
    cor.STECCOM_SUSPENDED_AMOUNT,
    cor.STECCOM_TOTAL_AMOUNT,
    -- Две отдельные колонки для планов: основной и suspended
    cor.STECCOM_PLAN_NAME_MONTHLY,
    cor.STECCOM_PLAN_NAME_SUSPENDED,
    -- Добавляем данные из биллинга
    v.SERVICE_ID,
    v.CODE_1C,
    v.ORGANIZATION_NAME,
    v.CUSTOMER_NAME,
    v.AGREEMENT_NUMBER,
    v.ORDER_NUMBER,
    v.STATUS AS SERVICE_STATUS,
    v.STOP_DATE AS SERVICE_STOP_DATE,
    v.IS_SUSPENDED,
    v.CUSTOMER_ID,
    v.ACCOUNT_ID,
    v.TARIFF_ID,
    -- Доп. поля: IMEI из биллинга (VSAT/IMEI) и номер сервиса при совпадении IMEI
    v.IMEI AS IMEI_VSAT,
    CASE 
      WHEN v.CONTRACT_ID LIKE 'SUB_%' AND v.IMEI IS NOT NULL AND cor.IMEI IS NOT NULL AND v.IMEI = cor.IMEI 
      THEN v.SERVICE_ID 
      ELSE NULL 
    END AS SERVICE_ID_VSAT_MATCH,
    -- Fees из STECCOM_EXPENSES
    NVL(sf.fee_activation_fee, 0) AS FEE_ACTIVATION_FEE,
    NVL(sf.fee_advance_charge, 0) AS FEE_ADVANCE_CHARGE,
    NVL(sf.fee_credit, 0) AS FEE_CREDIT,
    NVL(sf.fee_credited, 0) AS FEE_CREDITED,
    NVL(sf.fee_prorated, 0) AS FEE_PRORATED,
    NVL(sf.fees_total, 0) AS FEES_TOTAL,
    -- Разница между Fees Total и STECCOM Total Amount
    NVL(sf.fees_total, 0) - NVL(cor.STECCOM_TOTAL_AMOUNT, 0) AS DELTA_VS_STECCOM
FROM V_CONSOLIDATED_OVERAGE_REPORT cor
LEFT JOIN V_IRIDIUM_SERVICES_INFO v 
    ON cor.CONTRACT_ID = v.CONTRACT_ID
LEFT JOIN steccom_fees sf
    ON TO_CHAR(cor.BILL_MONTH) = sf.bill_month
    AND cor.CONTRACT_ID = sf.CONTRACT_ID
    AND cor.IMEI = sf.imei
/

-- Комментарии
COMMENT ON TABLE V_CONSOLIDATED_REPORT_WITH_BILLING IS 'Консолидированный отчет по Iridium с данными клиентов из биллинга. КАЖДАЯ СТРОКА = ОТДЕЛЬНЫЙ ПЕРИОД (BILL_MONTH)'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.SERVICE_ID IS 'ID сервиса из биллинга'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.SERVICE_STATUS IS 'Статус сервиса из биллинга (10=активный, -10=приостановленный)'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.SERVICE_STOP_DATE IS 'Конец предоставления услуги (stop_date) из биллинга'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.IS_SUSPENDED IS 'Признак приостановки: Y - есть активная услуга приостановления (TYPE_ID=9008), N - нет'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.CODE_1C IS 'Код клиента из 1С'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.ORGANIZATION_NAME IS 'Название организации (для юр.лиц)'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.CUSTOMER_NAME IS 'Название организации или ФИО клиента (универсальное поле)'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.AGREEMENT_NUMBER IS 'Номер договора в СТЭККОМ'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.ORDER_NUMBER IS 'Номер заказа/приложения'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.IMEI_VSAT IS 'IMEI из биллинга (VSAT/IMEI из V_IRIDIUM_SERVICES_INFO)'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.SERVICE_ID_VSAT_MATCH IS 'SERVICE_ID если login LIKE SUB_% и IMEI (VSAT) совпадает с отчетным IMEI'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.BILL_MONTH IS 'Период в формате YYYY-MM для отображения'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.BILL_MONTH_YYYMM IS 'Период в формате YYYYMM (число) для связи с другими таблицами'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.FEE_ACTIVATION_FEE IS 'Fee: Activation Fee из STECCOM_EXPENSES'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.FEE_ADVANCE_CHARGE IS 'Fee: Advance Charge из STECCOM_EXPENSES'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.FEE_CREDIT IS 'Fee: Credit из STECCOM_EXPENSES'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.FEE_CREDITED IS 'Fee: Credited из STECCOM_EXPENSES'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.FEE_PRORATED IS 'Fee: Prorated из STECCOM_EXPENSES'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.FEES_TOTAL IS 'Fees Total ($) - сумма всех fees'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.DELTA_VS_STECCOM IS 'Δ vs STECCOM ($) - разница между Fees Total и STECCOM Total Amount'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.TRAFFIC_USAGE_BYTES IS 'Трафик в байтах (только SBD Data Usage)'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.EVENTS_COUNT IS 'Общее количество событий'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.DATA_USAGE_EVENTS IS 'События SBD Data Usage'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.MAILBOX_EVENTS IS 'События SBD Mailbox Checks'
/
COMMENT ON COLUMN V_CONSOLIDATED_REPORT_WITH_BILLING.REGISTRATION_EVENTS IS 'События SBD Registrations'
/

SET DEFINE ON
