-- ============================================================================
-- LOAD_LOGS - Журнал загрузок данных
-- Назначение: Отслеживание загрузок CSV файлов в таблицы
-- База данных: Oracle (production)
-- ============================================================================

CREATE TABLE LOAD_LOGS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TABLE_NAME VARCHAR2(50) NOT NULL,
    FILE_NAME VARCHAR2(200) NOT NULL,
    RECORDS_LOADED NUMBER,
    LOAD_STATUS VARCHAR2(20) CHECK (LOAD_STATUS IN ('SUCCESS', 'FAILED', 'PARTIAL')),
    ERROR_MESSAGE VARCHAR2(4000),
    LOAD_START_TIME DATE DEFAULT SYSDATE,
    LOAD_END_TIME DATE,
    LOADED_BY VARCHAR2(50) DEFAULT USER
);

-- Индексы
CREATE INDEX IDX_LOAD_TABLE ON LOAD_LOGS(TABLE_NAME);
CREATE INDEX IDX_LOAD_FILE ON LOAD_LOGS(FILE_NAME);
CREATE INDEX IDX_LOAD_DATE ON LOAD_LOGS(LOAD_START_TIME);
CREATE INDEX IDX_LOAD_STATUS ON LOAD_LOGS(LOAD_STATUS);

-- Комментарии
COMMENT ON TABLE LOAD_LOGS IS 'Журнал загрузки данных из CSV файлов';
COMMENT ON COLUMN LOAD_LOGS.TABLE_NAME IS 'Имя таблицы в которую загружались данные';
COMMENT ON COLUMN LOAD_LOGS.FILE_NAME IS 'Имя загруженного файла';
COMMENT ON COLUMN LOAD_LOGS.RECORDS_LOADED IS 'Количество загруженных записей';
COMMENT ON COLUMN LOAD_LOGS.LOAD_STATUS IS 'Статус загрузки (SUCCESS/FAILED/PARTIAL)';
COMMENT ON COLUMN LOAD_LOGS.ERROR_MESSAGE IS 'Сообщение об ошибке если загрузка не удалась';

PROMPT Таблица LOAD_LOGS создана успешно!


