-- Проверка формата BILL_MONTH для IMEI 301434061220930
SELECT 
    'V_CONSOLIDATED_OVERAGE_REPORT' AS source,
    cor.BILL_MONTH,
    LENGTH(cor.BILL_MONTH) AS len,
    SUBSTR(cor.BILL_MONTH, 1, 6) AS first_6,
    TO_CHAR(TO_DATE(SUBSTR(cor.BILL_MONTH, 1, 6), 'YYYYMM'), 'YYYY-MM') AS formatted
FROM V_CONSOLIDATED_OVERAGE_REPORT cor
WHERE cor.IMEI = '301434061220930'
  AND ROWNUM <= 5;

