-- Доходы за февраль 2026 без задвоения IMEI (только услуги с CLOSE_DATE > конец периода или NULL)
SELECT TO_CHAR(TO_DATE(TO_CHAR(v.BILL_MONTH), 'YYYYMM'), 'YYYY-MM') AS "Период",
  v.CONTRACT_ID, v.IMEI, v.ORGANIZATION_NAME, v.CODE_1C,
  v.REVENUE_SBD_TRAFFIC, v.REVENUE_SBD_ABON, v.REVENUE_SBD_TOTAL, v.REVENUE_TOTAL
FROM V_REVENUE_FROM_INVOICES v
JOIN SERVICES s ON v.SERVICE_ID = s.SERVICE_ID
  AND (s.CLOSE_DATE IS NULL OR s.CLOSE_DATE > LAST_DAY(TO_DATE(TO_CHAR(v.BILL_MONTH), 'YYYYMM')))
WHERE TO_CHAR(TO_DATE(TO_CHAR(v.BILL_MONTH), 'YYYYMM'), 'YYYY-MM') = '2026-02'
ORDER BY v.IMEI, v.CONTRACT_ID;
