-- Поиск одной записи в октябрьском финансовом периоде с ненулевыми Fees
SET PAGESIZE 1000
SET LINESIZE 200

SELECT 
    BILL_MONTH,
    FINANCIAL_PERIOD,
    IMEI,
    CONTRACT_ID,
    FEE_ACTIVATION_FEE,
    FEE_ADVANCE_CHARGE,
    FEE_ADVANCE_CHARGE_PREVIOUS_MONTH,
    FEE_CREDIT,
    FEE_CREDITED,
    FEE_PRORATED
FROM V_CONSOLIDATED_REPORT_WITH_BILLING
WHERE FINANCIAL_PERIOD = '2025-10'
  AND (
      (FEE_ACTIVATION_FEE IS NOT NULL AND FEE_ACTIVATION_FEE != 0)
      OR (FEE_ADVANCE_CHARGE IS NOT NULL AND FEE_ADVANCE_CHARGE != 0)
      OR (FEE_CREDIT IS NOT NULL AND FEE_CREDIT != 0)
      OR (FEE_CREDITED IS NOT NULL AND FEE_CREDITED != 0)
      OR (FEE_PRORATED IS NOT NULL AND FEE_PRORATED != 0)
  )
  AND ROWNUM = 1;

