-- ============================================================================
-- TARIFF_PLANS - Справочник тарифных планов
-- Назначение: Хранение информации о тарифных планах SBD с ценами превышения
-- База данных: Oracle (production)
-- ============================================================================

CREATE TABLE TARIFF_PLANS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PLAN_NAME VARCHAR2(100) NOT NULL UNIQUE,
    PLAN_CODE VARCHAR2(20),
    INCLUDED_KB NUMBER NOT NULL,
    
    -- Первая ступень тарификации
    TIER1_FROM_KB NUMBER,
    TIER1_TO_KB NUMBER,
    TIER1_PRICE_USD NUMBER(10,4),
    
    -- Вторая ступень тарификации
    TIER2_FROM_KB NUMBER,
    TIER2_TO_KB NUMBER,
    TIER2_PRICE_USD NUMBER(10,4),
    
    -- Третья ступень тарификации (без верхнего порога)
    TIER3_FROM_KB NUMBER,
    TIER3_PRICE_USD NUMBER(10,4),
    
    ACTIVE VARCHAR2(1) DEFAULT 'Y' CHECK (ACTIVE IN ('Y', 'N')),
    CREATED_DATE DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(50) DEFAULT USER,
    COMMENTS VARCHAR2(500)
);

-- Индекс для быстрого поиска по названию плана
CREATE INDEX IDX_TARIFF_PLAN_NAME ON TARIFF_PLANS(PLAN_NAME);
CREATE INDEX IDX_TARIFF_PLAN_CODE ON TARIFF_PLANS(PLAN_CODE);
CREATE INDEX IDX_TARIFF_ACTIVE ON TARIFF_PLANS(ACTIVE);

-- Комментарии
COMMENT ON TABLE TARIFF_PLANS IS 'Справочник тарифных планов SBD с ценами превышения';
COMMENT ON COLUMN TARIFF_PLANS.PLAN_NAME IS 'Полное название тарифного плана из SPNet (уникальное)';
COMMENT ON COLUMN TARIFF_PLANS.PLAN_CODE IS 'Короткий код тарифа (например, SBD-1, SBD-10)';
COMMENT ON COLUMN TARIFF_PLANS.INCLUDED_KB IS 'Объем трафика включенный в абонентку (КБ, 1KB=1000bytes)';
COMMENT ON COLUMN TARIFF_PLANS.TIER1_PRICE_USD IS 'Цена за 1 КБ на первой ступени превышения (USD)';
COMMENT ON COLUMN TARIFF_PLANS.TIER2_PRICE_USD IS 'Цена за 1 КБ на второй ступени превышения (USD)';
COMMENT ON COLUMN TARIFF_PLANS.TIER3_PRICE_USD IS 'Цена за 1 КБ на третьей ступени превышения (USD)';
COMMENT ON COLUMN TARIFF_PLANS.ACTIVE IS 'Активен ли тариф (Y/N)';

PROMPT Таблица TARIFF_PLANS создана успешно!


