-- ============================================================================
-- EMAIL_CAMPAIGNS - Таблица рекламных email кампаний
-- Назначение: Хранение данных о рекламных кампаниях и их отправке
-- База данных: Oracle (production)
-- ============================================================================

CREATE TABLE EMAIL_CAMPAIGNS (
    CAMPAIGN_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CAMPAIGN_NAME VARCHAR2(200) NOT NULL,
    SUBJECT VARCHAR2(500) NOT NULL,
    GREETING VARCHAR2(1000),
    EMAIL_LIST CLOB NOT NULL,  -- Список email через запятую или JSON
    DOCX_CONTENT BLOB,  -- Содержимое файла письма (docx)
    DOCX_FILENAME VARCHAR2(255),  -- Имя исходного файла
    FROM_EMAIL VARCHAR2(255) DEFAULT 'sales@steccom.ru',
    SMTP_HOST VARCHAR2(255) DEFAULT 'mail.steccom.ru',
    SMTP_PORT NUMBER DEFAULT 25,
    STATUS VARCHAR2(20) DEFAULT 'DRAFT' CHECK (STATUS IN ('DRAFT', 'SENT', 'FAILED', 'PARTIAL', 'TEST_SENT')),
    EMAILS_TOTAL NUMBER DEFAULT 0,  -- Общее количество email в списке
    EMAILS_SENT NUMBER DEFAULT 0,  -- Количество успешно отправленных
    EMAILS_FAILED NUMBER DEFAULT 0,  -- Количество неудачных отправок
    TEST_MODE NUMBER DEFAULT 0,  -- Флаг тестовой рассылки (0 - обычная, 1 - тестовая)
    TEST_EMAILS CLOB,  -- Список контрольных email для тестовой рассылки
    CREATED_BY VARCHAR2(50) DEFAULT USER,
    CREATED_AT DATE DEFAULT SYSDATE,
    SENT_BY VARCHAR2(50),  -- Пользователь отправивший кампанию
    SENT_AT DATE,  -- Дата и время отправки кампании
    ERROR_MESSAGE VARCHAR2(4000),  -- Сообщение об ошибке если отправка не удалась
    NOTES CLOB  -- Дополнительные заметки о кампании
);

-- Индексы
CREATE INDEX IDX_CAMPAIGN_STATUS ON EMAIL_CAMPAIGNS(STATUS);
CREATE INDEX IDX_CAMPAIGN_CREATED ON EMAIL_CAMPAIGNS(CREATED_AT);
CREATE INDEX IDX_CAMPAIGN_NAME ON EMAIL_CAMPAIGNS(CAMPAIGN_NAME);
CREATE INDEX IDX_CAMPAIGN_CREATED_BY ON EMAIL_CAMPAIGNS(CREATED_BY);
CREATE INDEX IDX_CAMPAIGN_SENT_BY ON EMAIL_CAMPAIGNS(SENT_BY);
CREATE INDEX IDX_CAMPAIGN_SENT_AT ON EMAIL_CAMPAIGNS(SENT_AT);

-- Комментарии
COMMENT ON TABLE EMAIL_CAMPAIGNS IS 'Таблица рекламных email кампаний';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.CAMPAIGN_ID IS 'Первичный ключ (auto-increment)';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.CAMPAIGN_NAME IS 'Название кампании';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.SUBJECT IS 'Тема письма';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.GREETING IS 'Приветствие в письме';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.EMAIL_LIST IS 'Список email получателей (разделитель - запятая)';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.DOCX_CONTENT IS 'Содержимое файла письма в формате DOCX (BLOB)';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.DOCX_FILENAME IS 'Имя исходного файла письма';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.STATUS IS 'Статус кампании: DRAFT - черновик, SENT - отправлено, FAILED - ошибка, PARTIAL - частично отправлено, TEST_SENT - тестовая рассылка отправлена';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.EMAILS_TOTAL IS 'Общее количество email в списке получателей';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.EMAILS_SENT IS 'Количество успешно отправленных писем';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.EMAILS_FAILED IS 'Количество писем с ошибкой отправки';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.TEST_MODE IS 'Флаг тестовой рассылки: 0 - обычная рассылка, 1 - тестовая рассылка по контрольным email';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.TEST_EMAILS IS 'Список контрольных email для тестовой рассылки (разделитель - запятая)';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.CREATED_BY IS 'Пользователь создавший кампанию';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.CREATED_AT IS 'Дата создания кампании';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.SENT_BY IS 'Пользователь отправивший кампанию (кто нажал кнопку отправки)';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.SENT_AT IS 'Дата и время отправки кампании';
COMMENT ON COLUMN EMAIL_CAMPAIGNS.ERROR_MESSAGE IS 'Сообщение об ошибке если отправка не удалась';

PROMPT Таблица EMAIL_CAMPAIGNS создана успешно!

